name: Renovate

on:
  # Immediately run again after renovate.yml itself was updated
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
  workflow_dispatch:
    inputs:
      log-level:
        description: Log level
        required: true
        default: INFO
        type: choice
        options:
          - TRACE
          - DEBUG
          - INFO
          - WARN
          - ERROR
  schedule:
    # run at 02:02 every Friday, the asterisk has special meaning in YAML so this must be quoted
    - cron: '2 2 * * 5'

concurrency:
  group: renovate
  cancel-in-progress: true

permissions: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # No need for credentials after this step
          persist-credentials: false
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: create-github-app-token
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: renovatebot/github-action@dd5302ec17783b2fc721b19ae7209b57b1587765 # v46.1.17
        with:
          # recommended to not name it one of the repository configuration filenames listed in the Renovate Docs
          configurationFile: renovate-config.json
          token: ${{ steps.create-github-app-token.outputs.token }}
        env:
          LOG_LEVEL: ${{ github.event.inputs.log-level }}
